./json_formatter.sh communityArvDistribution.sql
./json_formatter.sh exposed_infants_register_in_ptme_program.sql
./json_formatter.sh hiv_transmission_risks_factor.sql
./json_formatter.sh number_eligible_children_for_pcr.sql
./json_formatter.sh number_exposed_infants_tested_by_pcr.sql
./json_formatter.sh number_infants_from_mother_on_prophylaxis.sql
./json_formatter.sh numberOfPatientByArvStatus.sql
./json_formatter.sh number_patient_beneficie_pcr.sql
./json_formatter.sh numberPatientReceivingARVByPeriod.sql
./json_formatter.sh number_pregnancy_women_had_prenatal_cons.sql
./json_formatter.sh number_prenatal_visit_by_site.sql
./json_formatter.sh number_visits_by_pregnant_women_to_the_clinic.sql
./json_formatter.sh pregnancy_women_on_haart.sql
./json_formatter.sh firstVisitAge.sql
./json_formatter.sh institution_frequenting.sql
